### ISSUE TITLE
code  compilation issue -sim mode

### ISSUE THREAD

**Issue by amarsri28** [omec-project/upf#649]
current code base is not compiling in sim mode - logs attached 
[Uploading compilation-issue-sim-mode.txt…]()

**Comment by amarsri28** [comment]
probable reason - latest PR removes essential files required for building i.e files under patch/bess folder

**Comment by amarsri28** [comment]
[compilation-issue-sim-mode.txt](https://github.com/omec-project/upf/files/9940717/compilation-issue-sim-mode.txt)

**Comment by amarsri28** [comment]
after reverting latest PR by git revert HEAD , its compiling fine. success logs attached for reference .
[success-logs-after-git-revert.txt](https://github.com/omec-project/upf/files/9940778/success-logs-after-git-revert.txt)

**Comment by amarsri28** [comment]
@gab-arrobo

**Comment by gab-arrobo** [comment]
> current code base is not compiling in sim mode - logs attached Uploading compilation-issue-sim-mode.txt…

@amarsri28, as I indicated in Slack (including screen captures), I do not see the issue... The installation process successfully completes in an Ubuntu 18.04 VM and in an Ubuntu 20.04/22.04 (bare metal).

**Comment by gab-arrobo** [comment]
> probable reason - latest PR removes essential files required for building i.e files under patch/bess folder

There is no reason for the installation process to fail because the files from `patch/bess` (removed from here) are already committed in `bess` repo.

As I indicated in Slack, the installation process may fail if you create a new BESS patch in the UPF because the patches/changes should be done directly in the BESS repo. There is NO need to keep patching BESS because now we are directly committing the changes in the BESS repo
